version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_reddit
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # volumes:
    #   - ./data/mongo2:/data/db
    ports:
        - 27017:27017
  reddit:
    build: .
    image: reddit_scraping
    container_name: reddit
    ports:
    #  - 8888:8888
     - 5066:5066
    # command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    command: ["python","app/reddit.py"]
    volumes:
      - ./:/home/dev/code/
  selenium:
    container_name: selenium2
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    network_mode: host

    